# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CharDatasetor-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'  
  pod 'Firebase/Storage'



  # Pods for CharDatasetor-iOS

  target 'CharDatasetor-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CharDatasetor-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
